export const VALIDATE_TRAVELER_LOGIN = "VALIDATE_TRAVELER_LOGIN";
export const VALIDATE_OWNER_LOGIN = "VALIDATE_OWNER_LOGIN";
export const TRAVELER_SIGN_UP = "TRAVELER_SIGN_UP";
export const OWNER_SIGN_UP = "OWNER_SIGN_UP";

export const SAVE_SEARCH_INPUT = "SAVE_SEARCH_INPUT";
export const GET_SEARCH_INPUT = "GET_SEARCH_INPUT";
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS_BY_ID = "GET_SEARCH_RESULTS_BY_ID";
export const BOOK_PROPERTY = "BOOK_PROPERTY";
export const RESET_BOOKING_STATUS = "RESET_BOOKING_STATUS";
export const FILTER_SEARCH_RESULTS = "FILTER_SEARCH_RESULTS";
export const RESET_FILTER_RESULTS = "RESET_FILTER_RESULTS";

export const GET_PROFILE = "GET_PROFILE";
export const SAVE_PROFILE = "SAVE_PROFILE";
export const GET_USER_PHOTO_NAME = "GET_USER_PHOTO_NAME";

export const SAVE_USERNAME = "SAVE_USERNAME";
export const GET_USERNAME = "GET_USERNAME";

export const CHECK_IS_OWNER = "CHECK_IS_OWNER";
export const GET_OWNER_DASHBOARD = "GET_OWNER_DASHBOARD";
export const GET_OWNER_DASHBOARD_BY_ID = "GET_OWNER_DASHBOARD_BY_ID";
export const GET_TRAVELER_DASHBOARD = "GET_TRAVELER_DASHBOARD";
export const GET_SEARCH_RESULTS_BY_NAME_OWNER =
  "GET_SEARCH_RESULTS_BY_NAME_OWNER";
export const GET_SEARCH_RESULTS_BY_NAME_TRAVELER =
  "GET_SEARCH_RESULTS_BY_NAME_TRAVELER";
export const FILTER_DATE_TRAVELER_DASHBOARD = "FILTER_DATE_TRAVELER_DASHBOARD";
export const FILTER_DATE_OWNER_DASHBOARD = "FILTER_DATE_OWNER_DASHBOARD";

export const LIST_PROPERTY = "LIST_PROPERTY";
export const SAVE_PHOTO_NAME = "SAVE_PHOTO_NAME";
export const GET_PHOTO_NAME = "GET_PHOTO_NAME";
export const GET_ALL_PHOTO_NAMES_TRAVELER = "GET_ALL_PHOTO_NAMES_TRAVELER";
export const GET_ALL_PHOTO_NAMES_OWNER = "GET_ALL_PHOTO_NAMES_OWNER";
export const GET_ALL_PHOTO_NAMES_SEARCH = "GET_ALL_PHOTO_NAMES_SEARCH";
export const GET_PHOTO_NAMES_BY_PROPERTY_ID = "GET_PHOTO_NAMES_BY_PROPERTY_ID";
export const DOWNLOAD_PHOTO = "DOWNLOAD_PHOTO";
export const UPLOAD_PHOTO = "UPLOAD_PHOTO";

export const SEND_QUESTION = "SEND_QUESTION";
export const SEND_ANSWER = "SEND_ANSWER";
export const GET_QUESTION = "GET_QUESTION";
export const GET_ANSWER = "GET_ANSWER";
